#pragma once

#include "textures.h"

#define MAX_CUBES 5

#define MC_BLOCK_AIR_ID 0
#define MC_BLOCK_DIRT_ID 1
#define MC_BLOCK_SAND_ID 2
#define MC_BLOCK_GRAVEL_ID 3
#define MC_BLOCK_GRASS_PATH_ID 4

typedef struct {

	unsigned block_id;
	unsigned texture_id[6];

} CubeDescription;

CubeDescription CUBES[MAX_CUBES] = {
	{ MC_BLOCK_AIR_ID, { NULL } },
	{ MC_BLOCK_DIRT_ID, { MC_TEXTURE_DIRT_ID, MC_TEXTURE_DIRT_ID, MC_TEXTURE_DIRT_ID, MC_TEXTURE_DIRT_ID, MC_TEXTURE_DIRT_ID, MC_TEXTURE_DIRT_ID } },
	{ MC_BLOCK_SAND_ID, { MC_TEXTURE_SAND_ID, MC_TEXTURE_SAND_ID, MC_TEXTURE_SAND_ID, MC_TEXTURE_SAND_ID, MC_TEXTURE_SAND_ID, MC_TEXTURE_SAND_ID } },
	{ MC_BLOCK_GRAVEL_ID,  { MC_TEXTURE_GRAVEL_ID, MC_TEXTURE_GRAVEL_ID, MC_TEXTURE_GRAVEL_ID, MC_TEXTURE_GRAVEL_ID, MC_TEXTURE_GRAVEL_ID, MC_TEXTURE_GRAVEL_ID } },
	{ MC_BLOCK_GRASS_PATH_ID, { MC_TEXTURE_GRASS_PATH_TOP_ID, MC_TEXTURE_DIRT_ID, MC_TEXTURE_GRASS_PATH_SIDE_ID, MC_TEXTURE_GRASS_PATH_SIDE_ID, MC_TEXTURE_GRASS_PATH_SIDE_ID, MC_TEXTURE_GRASS_PATH_SIDE_ID } }
};