#pragma once

#define MC_TEXTURES_COUNT 3

#define MC_TEXTURE_DIRT_ID 0
#define MC_TEXTURE_DIRT_FN "dirt.png"

#define MC_TEXTURE_SAND_ID 1
#define MC_TEXTURE_SAND_FN "sand.png"

#define MC_TEXTURE_GRAVEL_ID 2
#define MC_TEXTURE_GRAVEL_FN "gravel.png"

const char* MC_TEXTURE_ID_FN_MAP[MC_TEXTURES_COUNT] = {
	MC_TEXTURE_DIRT_FN,
	MC_TEXTURE_SAND_FN,
	MC_TEXTURE_GRAVEL_FN
};